import type { CSSProperties } from "react";

export const s = {
  card: (status: string): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 150px",
    alignItems: "start",
    columnGap: 16,
    rowGap: 10,
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${status === "accepted" ? "var(--ok)" : status === "rejected" ? "var(--text-muted)" : "var(--border-strong)"}`,
    background: "var(--bg-elevated)",
    opacity: status === "rejected" ? 0.6 : 1,
  }),
  rule: {
    gridColumn: 1,
    alignSelf: "center",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  ruleInput: {
    gridColumn: 1,
    fontSize: 14,
    fontWeight: 700,
    width: "100%",
  } satisfies CSSProperties,
  actions: {
    gridColumn: 2,
    gridRow: 1,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 6,
    minHeight: 30,
  } satisfies CSSProperties,
  decision: (rowEnd: number): CSSProperties => ({
    gridColumn: 2,
    gridRow: `2 / ${rowEnd}`,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  }),
  decisionBtn: {
    fontSize: 14,
    padding: "9px 14px",
  } satisfies CSSProperties,
  mainCol: {
    gridColumn: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  editBlock: {
    gridColumn: 1,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  evidenceHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 10px",
    borderRadius: "6px 6px 0 0",
    background: "var(--bg-hover)",
    border: "1px solid var(--border)",
    borderBottom: "none",
  } satisfies CSSProperties,
  evidencePath: {
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  copyBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: 10,
    borderRadius: "0 0 6px 6px",
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  rationale: {
    gridColumn: 1,
    fontSize: 12,
    color: "var(--text-secondary)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  rationaleInput: {
    fontSize: 12,
    width: "100%",
  } satisfies CSSProperties,
  bottomRow: {
    gridColumn: 1,
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  confidenceLabel: {
    fontSize: 12,
    color: "var(--text-secondary)",
    flexShrink: 0,
  } satisfies CSSProperties,
  confidenceBarWrap: {
    flex: 1,
    maxWidth: 200,
  } satisfies CSSProperties,
  confidencePct: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-primary)",
    flexShrink: 0,
  } satisfies CSSProperties,
  editRow: {
    display: "flex",
    gap: 8,
    justifyContent: "flex-end",
  } satisfies CSSProperties,
};
