import type { CSSProperties } from "react";

export const s = {
  wrap: {
    padding: "24px 28px",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    maxWidth: 900,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  h2: {
    fontSize: 16,
    fontWeight: 700,
    margin: 0,
  } satisfies CSSProperties,
  enabledLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  row: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  } satisfies CSSProperties,
  editorContainer: {
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,
  editorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 14px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  editorTab: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  tokenBadge: {
    fontSize: 11,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  editorBody: {
    display: "flex",
    minHeight: 320,
    background: "var(--bg-base)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    lineHeight: "20px",
  } satisfies CSSProperties,
  gutter: {
    padding: "12px 10px",
    textAlign: "right",
    userSelect: "none",
    color: "var(--text-muted)",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    minWidth: 44,
  } satisfies CSSProperties,
  gutterLine: {
    height: 20,
    display: "block",
  } satisfies CSSProperties,
  textarea: {
    flex: 1,
    padding: "12px 14px",
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    lineHeight: "20px",
    resize: "none",
    whiteSpace: "pre",
    overflowWrap: "normal",
    overflowX: "auto",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
  } satisfies CSSProperties,
  savedNote: {
    fontSize: 13,
    color: "var(--success, #10b981)",
    fontWeight: 500,
  } satisfies CSSProperties,
  untrustedNotice: {
    padding: 12,
    borderRadius: 6,
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
} as const;
