import type { CSSProperties } from "react";
import type { LineKind } from "./highlight";

export const s = {
  wrap: {
    padding: "24px 28px",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    maxWidth: 900,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  h2: {
    fontSize: 16,
    fontWeight: 700,
    margin: 0,
  } satisfies CSSProperties,
  enabledLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  editorContainer: {
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,
  editorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 14px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  editorTab: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  tokenBadge: {
    fontSize: 11,
    fontFamily: "var(--font-mono)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  editorBody: {
    display: "flex",
    minHeight: 320,
    background: "var(--bg-base)",
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    lineHeight: "20px",
  } satisfies CSSProperties,
  gutter: {
    padding: "12px 10px",
    textAlign: "right",
    userSelect: "none",
    color: "var(--text-muted)",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    minWidth: 44,
  } satisfies CSSProperties,
  gutterLine: {
    height: 20,
    display: "block",
  } satisfies CSSProperties,
  editorPane: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    display: "flex",
  } satisfies CSSProperties,
  highlightLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    margin: 0,
    padding: "12px 14px",
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    lineHeight: "20px",
    whiteSpace: "pre",
    color: "var(--text-primary)",
    pointerEvents: "none",
  } satisfies CSSProperties,
  highlightLine: (kind: LineKind): CSSProperties =>
    kind === "text"
      ? { minHeight: 20 }
      : { minHeight: 20, color: "var(--accent-text)", fontWeight: kind === "h3" ? 500 : 600 },
  textarea: {
    position: "relative",
    flex: 1,
    padding: "12px 14px",
    border: "none",
    outline: "none",
    background: "transparent",
    color: "transparent",
    caretColor: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    lineHeight: "20px",
    resize: "none",
    whiteSpace: "pre",
    overflowWrap: "normal",
    overflowX: "auto",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
  } satisfies CSSProperties,
  savedNote: {
    fontSize: 13,
    color: "var(--ok)",
    fontWeight: 500,
  } satisfies CSSProperties,
  untrustedNotice: {
    padding: 12,
    borderRadius: 6,
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  dangerZone: {
    marginTop: 12,
    padding: "14px 18px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg, rgba(239, 68, 68, 0.06))",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  } satisfies CSSProperties,
  dangerTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  dangerBody: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    marginTop: 2,
  } satisfies CSSProperties,
} as const;
