import type { CSSProperties } from "react";

export const s = {
  wrap: {
    padding: 24,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  tabsRow: {
    display: "flex",
    gap: 12,
    borderBottom: "1px solid var(--border)",
    paddingBottom: 12,
  } satisfies CSSProperties,
  tabBtn: (active: boolean): CSSProperties => ({
    padding: "6px 14px",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    background: active ? "var(--accent)" : "transparent",
    color: active ? "#fff" : "var(--text-secondary)",
    border: "none",
    transition: "all 0.15s",
  }),
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  select: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  textarea: {
    width: "100%",
    minHeight: 140,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12.5,
    lineHeight: 1.5,
    resize: "vertical",
  } satisfies CSSProperties,
  dropzone: (isDragOver: boolean): CSSProperties => ({
    border: `2px dashed ${isDragOver ? "var(--accent)" : "var(--border-strong)"}`,
    borderRadius: 8,
    padding: "32px 20px",
    textAlign: "center",
    cursor: "pointer",
    background: isDragOver ? "var(--bg-hover)" : "var(--bg-surface)",
    transition: "all 0.15s",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
  }),
  previewBox: {
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    padding: 12,
    maxHeight: 180,
    overflow: "auto",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    gap: 10,
    justifyContent: "flex-end",
    marginTop: 8,
  } satisfies CSSProperties,
} as const;
