import type { CSSProperties } from "react";
import { tint } from "@/lib/color";

export const s = {
  center: { padding: 32, display: "flex", justifyContent: "center" } satisfies CSSProperties,
  filter: { marginLeft: "auto", width: 220 } satisfies CSSProperties,
  wrap: {
    padding: "24px 28px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    maxWidth: 900,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  h2: {
    fontSize: 16,
    fontWeight: 700,
    margin: 0,
  } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-secondary)",
    margin: "-6px 0 4px",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  row: (isDragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 6,
    background: isDragging ? "var(--bg-hover)" : "var(--bg-elevated)",
    border: "1px solid var(--border)",
  }),
  handle: (disabled: boolean): CSSProperties => ({
    display: "flex",
    color: "var(--text-muted)",
    cursor: disabled ? "not-allowed" : "grab",
    opacity: disabled ? 0.35 : 1,
    flexShrink: 0,
  }),
  pathCol: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    gap: 8,
  } satisfies CSSProperties,
  fileName: {
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "var(--font-mono)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  dir: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  categoryBadge: (color: string): CSSProperties => ({
    fontSize: 11,
    fontWeight: 600,
    color,
    background: tint(color),
    padding: "2px 8px",
    borderRadius: 4,
    flexShrink: 0,
  }),
  missing: { fontSize: 11, color: "var(--text-muted)", fontStyle: "italic", flexShrink: 0 } satisfies CSSProperties,
  serializesAs: {
    marginTop: 6,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  serializesAsTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  serializesGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  serializesGroupTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-secondary)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  serializesPath: {
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  previewBody: {
    padding: "16px 24px",
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    whiteSpace: "pre-wrap",
    lineHeight: 1.6,
    color: "var(--text-primary)",
    maxHeight: 480,
    overflow: "auto",
  } satisfies CSSProperties,
} as const;
